### ISSUE TITLE
PA Review: User Authentication 

### ISSUE THREAD

**Issue by gabrieltal** [gabrieltal/betwixt#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loops: ajax, actions, reducer
- [x] Presentation Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x]  Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [x] users can't use certain features without logging in (to be completed once I get stories up, technically they cannot sign out without signing in so there are features they can't do without signing in)
- [x] Now hosting on Heroku

**Comment by wongshington** [comment]
- [x] add some space between the errors and the buttons when they show up
- [x] on signup form each error should be it's own line instead of running together
- [x]  make the errors a different color to make them stand out (red is a popular option)
- [x] add at least a slightly grayed out background to the modal so that it is clear a user needs to login
- [x] the nav bar shouldnt resize when you're logged in to when you log out

**Comment by wongshington** [comment]
- [x] try and model the session form a bit more like the site
   - they have a bit more text on their form to preface the site
   - they use a lighter/more lively color scheme
   - they don't have text inputs but they do have larger/wider buttons that take up more of the session form

**Comment by wongshington** [comment]
A1 👍
