### ISSUE TITLE
PA REVIEW: Stories

### ISSUE THREAD

**Issue by gabrieltal** [gabrieltal/betwixt#9]
- [x] Logged in users can create stories
- [x] Users can view stories on homepage
- [x] Users can view other user stories on user show page
- [x] Users can only edit and delete their own stories
- [x] Users cannot access edit and delete pages unless logged in

**Comment by wongshington** [comment]
- [x] double check that a user can write a story through your form
   - i had some trouble when i tried with a photo
   - i also tries without a photo with no luck

**Comment by wongshington** [comment]
- When on a story show page
   - [ ] title above the photo
   - optional subtitle? (could be a nice touch)
   - [ ] bit more spacing and more centered next to photo for author name/ "member since..."
   - [ ] don't need the author info at the bottom of the story unless/until a user can follow that user (i think thats how medium has it right?)
